
dist: bionic

matrix:
  include:
    - language: node_js
      node_js:
        - 16
      cache:
        npm: false 
        directories:
          - ./.yarn/cache

      before_install:
        
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
    
      install: yarn

      before_script: 
        - cd front-end
      script:
        - yarn test
        - yarn build


    - language: java
      cache:
        directories:
        - $HOME/.m2
      
      jdk: openjdk11
      before_script: cd back-end
      script:
        - ./mvnw clean compile package
