
dist: bionic

matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_script: 
        - cd front-end
      script:
        - yarn install
        - yarn test
        - yarn build
    - language: java
      jdk: openjdk11
      before_script: cd back-end
      script:
        - ./mvnw clean compile package
