
dist: bionic

matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      before_install: cd front-end
	- yarn install
      script:
        - yarn test
        - yarn build
    - language: java
      jdk: openjdk11
      before_script: cd back-end
      script:
        - ./mvnw clean compile package
