
dist: bionic

matrix:
  include:
    - language: node_js
      node_js:
        - 16
      cache:
        npm: false 
        directories:
          - ./.yarn/cache
          
    
      install: yarn

      before_script: 
        - cd front-end
      script:
        - yarn test
        - yarn build


    - language: java
      cache:
        directories:
        - $HOME/.m2
      
      jdk: openjdk11
      before_script: cd back-end
      script:
        - ./mvnw clean compile package
