# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

services:
  server:
    build:
      context: back-end 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/harmonie
    networks:
      - back-end
      - front-end
    

  react-app:
    build:
      context: front-end
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - "4545:80"
    restart: always
    depends_on:
      - server
    networks:
      - front-end  
  
  db:
    image: postgis/postgis
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: harmonie
      POSTGRES_PASSWORD: harpasswd
      POSTGRES_DB: harmonie
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./back-end/src/main/resources/pg_pgis_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-end

volumes:
  db-data:
networks:
  back-end:
  front-end:
 

