package eu.acclimatize.unison.location;

import java.util.List;

import org.springframework.hateoas.Link;
import org.springframework.hateoas.RepresentationModel;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A representational model class for locations.
 *
 */
public class LocationModel extends RepresentationModel<LocationModel> {

	@JsonProperty
	private String name;

	/**
	 * Creates an instance of LocationModel.
	 * 
	 * @param list The list of links to include the model.
	 * @param name The name of the location.
	 */
	public LocationModel(List<Link> list, String name) {
		super(list);
		this.name = name;
	}

	// Generated by Eclipse.
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	// Generated by Eclipse.
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		LocationModel other = (LocationModel) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	
}
